install_core:
  - curl
  - git
  - less

install_shell:
  - fd-find
  - fzf
  - jq
  - neovim
  - ripgrep
  - tmux
  - zoxide
  - zsh
  - lf

install_networking:
  - dnsutils
  - net-tools
  - nmap
  - traceroute
  - whois

install_monitoring:
  - btop
  - duff
  - iftop
  - iotop
  - iperf3
  - mtr
  - ncdu
