install_core:
  - build-essential
  - curl
  - file
  - git
  - less
  - man-db
  - unzip
  - zip

install_shell:
  - fd-find
  - fzf
  - jq
  - neovim
  - ripgrep
  - tmux
  - zoxide
  - zsh

install_networking:
  - dnsutils
  - net-tools
  - nmap
  - traceroute
  - whois

install_monitoring:
  - btop
  - duff
  - gping
  - iftop
  - iotop
  - iperf3
  - mtr
  - ncdu
  - atop
