---
- name: "Ensure the project directory exists"
  ansible.builtin.file:
    path: "{{ b216_backend_project_directory }}"
    state: directory
    owner: "{{ ansible_user | default('deployer') }}"
    mode: '0755'

- name: "Install git"
  ansible.builtin.apt:
    name: git
    state: present
    update_cache: true

- name: "Include Docker role"
  ansible.builtin.import_role:
    name: geerlingguy.docker

- name: "Clone umrs-back repository"
  ansible.builtin.git:
    repo: "{{ b216_backend_project_repo }}"
    dest: "{{ b216_backend_project_directory }}"
    update: true
    force: true
    version: "{{ b216_backend_project_version }}"
    accept_hostkey: true

- name: Tear down existing services
  community.docker.docker_compose_v2:
    project_src: "{{ b216_backend_project_directory }}"
    state: absent

- name: Create and start services
  community.docker.docker_compose_v2:
    project_src: "{{ b216_backend_project_directory }}"
    register: output

- name: Show results
  ansible.builtin.debug:
    var: output
