# Docker role variables
docker_enabled: true
docker_users: ["deployer"]

# Users role variables
users_new_user: "deployer"
users_user_password: "SUPER_SECRET_PASSWORD"
users_user_ssh_key_path: "~/.ssh/id_ed25519.pub"

# SSH role variables
ssh_port: 2264984

# B216 Backend role variables
b216_backend_project_directory: "/opt/umrs-back"
b216_backend_server_port: 8081
b216_backend_project_version: "main"

# Database credentials
b216_backend_database_name: "umrs-back"
b216_backend_database_username: "umrs-back"
b216_backend_database_password: "SUPER_SECRET_PASSWORD"
b216_backend_database_port: 5432

# Mail server configuration
b216_backend_mail_host: "smtp.umrs.example.com"
b216_backend_mail_port: 587
b216_backend_mail_username: "noreply@umrs.example.com"
b216_backend_mail_password: "SUPER_SECRET_PASSWORD"
b216_backend_mail_smtp_auth: true
b216_backend_mail_smtp_starttls_enable: true
b216_backend_mail_smtp_starttls_required: true
b216_backend_mail_ssl_trust: "*"

# Application admin credentials
b216_backend_admin_username: "admin@umrs.example.com"
b216_backend_admin_password: "SUPER_SECRET_PASSWORD"

# GitHub Container Registry credentials
ghcr_username: "volard"
ghcr_token: "SUPER_SECRET_PASSWORD"

# Geoform role variables
b216_geoform_project_directory: "/opt/geoform"
b216_geoform_server_port: 4173
b216_geoform_project_version: "main"
b216_geoform_ghcr_username: "volard"
b216_geoform_ghcr_token: "SUPER_SECRET_PASSWORD"
