---
- name: "Include Docker role"
  ansible.builtin.import_role:
    name: geerlingguy.docker

- name: Ensure geoform project directory exists
  ansible.builtin.file:
    path: "{{ b216_geoform_project_directory }}"
    state: directory
    owner: "{{ ansible_user | default(lookup('env', 'USER')) }}"
    group: "{{ ansible_user | default(lookup('env', 'USER')) }}"
    mode: '0755'

- name: Template docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ b216_geoform_project_directory }}/docker-compose.yml"
    mode: '0644'
  when: b216_geoform_project_directory is defined

- name: Log in to GitHub Container Registry (ghcr.io)
  community.docker.docker_login:
    registry_url: "ghcr.io"
    username: "{{ ghcr_username }}"
    password: "{{ ghcr_token }}"
  no_log: true

- name: Tear down existing services
  community.docker.docker_compose_v2:
    project_src: "{{ b216_geoform_project_directory }}"
    state: absent

- name: Ensure shared-net docker network exists
  community.docker.docker_network:
    name: shared-net
    state: present

- name: Create and start services
  community.docker.docker_compose_v2:
    project_src: "{{ b216_geoform_project_directory }}"
  register: b216_geoform_docker_output

- name: Show results
  ansible.builtin.debug:
    var: b216_geoform_docker_output
