argument_specs:
  main:
    options:
      users_new_user:
        type: str
        required: true
      users_user_password:
        type: str
        required: true
      users_user_ssh_key_path:
        type: path
        required: true