- name: Create user
  ansible.builtin.user:
    name: "{{ users_new_user }}"
    shell: /bin/bash
    groups: sudo
    append: true
    state: present
    create_home: true
    update_password: always
    password: "{{ users_user_password | password_hash('sha512') }}"
  when: users_user_password is defined

- name: Set up authorized SSH key
  ansible.posix.authorized_key:
    user: "{{ users_new_user }}"
    state: present
    key: "{{ lookup('file', users_user_ssh_key_path) }}"
