---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install Python 3
      ansible.builtin.raw: |
        apt-get update -qq
        apt-get install -y -qq python3 python3-apt
      changed_when: false

