- name: 'Services'
  hosts: all
  become: true
  tags: services
  tasks:
    - name: Include Docker role
      ansible.builtin.include_role:
        name: docker
      when: docker_enabled | default(true)
